name: build docs

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    builddocs:
        runs-on: ubuntu-latest
        steps:
          - run: echo "hello"
