name: RunFairSECO

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    RunFairSECO:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            #- uses: actions/setup-python@v4
            #  with:
            #    python-version: '3.10'
            #- uses: tortellini-tools/action@main
            #- uses: actions/upload-artifact@v3
            #  with:
            #      name: tortellini-result
            #      path: .tortellini/out
            - uses: ./
            - uses: actions/upload-artifact@v3
              with:
                  name: FairSECO Result
                  path: .FairSECO/
